DROP TABLE IF EXISTS order_row;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS appliance;
DROP TABLE IF EXISTS manufacturer;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS login_attempts;
DROP TABLE IF EXISTS refresh_token;

CREATE TABLE manufacturer
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE client
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)   NOT NULL,
    email      VARCHAR(150)   NOT NULL UNIQUE,
    password   VARCHAR(200)   NOT NULL,
    enabled    BOOLEAN        NOT NULL,

    card_last4 VARCHAR(4),
    card_hash  VARCHAR(64),

    balance    DECIMAL(12, 2) NOT NULL
);

CREATE INDEX idx_client_email ON client (email);

CREATE TABLE employee
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL UNIQUE,
    password   VARCHAR(200) NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    department VARCHAR(100) NOT NULL
);

CREATE INDEX idx_employee_email ON employee (email);

CREATE TABLE appliance
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150)   NOT NULL,
    category        VARCHAR(50)    NOT NULL,
    model           VARCHAR(150)   NOT NULL,
    manufacturer_id BIGINT         NOT NULL,
    power_type      VARCHAR(50)    NOT NULL,
    characteristic  VARCHAR(255)   NOT NULL,
    description     VARCHAR(500)   NOT NULL,
    power           INT            NOT NULL,
    price           DECIMAL(12, 2) NOT NULL,

    CONSTRAINT fk_appliance_manufacturer
        FOREIGN KEY (manufacturer_id)
            REFERENCES manufacturer (id)
);

CREATE INDEX idx_appliance_manufacturer ON appliance (manufacturer_id);
CREATE INDEX idx_appliance_category ON appliance (category);
CREATE INDEX idx_appliance_price ON appliance (price);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT NULL,
    client_id    BIGINT      NOT NULL,
    order_status VARCHAR(50) NOT NULL,

    delivery_name    VARCHAR(100),
    delivery_phone   VARCHAR(30),
    delivery_address VARCHAR(300),
    delivery_comment VARCHAR(500),

    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),

    CONSTRAINT fk_orders_client
        FOREIGN KEY (client_id) REFERENCES client (id)
);


CREATE INDEX idx_orders_client ON orders (client_id);
CREATE INDEX idx_orders_status ON orders (order_status);
CREATE INDEX idx_orders_client_status ON orders (client_id, order_status);

CREATE TABLE order_row
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orders_id    BIGINT         NOT NULL,
    appliance_id BIGINT         NOT NULL,
    number       BIGINT         NOT NULL,
    amount       DECIMAL(12, 2) NOT NULL,

    CONSTRAINT fk_order_row_orders
        FOREIGN KEY (orders_id)
            REFERENCES orders (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_order_row_appliance
        FOREIGN KEY (appliance_id)
            REFERENCES appliance (id)
);

CREATE INDEX idx_order_row_orders ON order_row (orders_id);

CREATE TABLE login_attempts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(150) NOT NULL,
    ip           VARCHAR(45)  NOT NULL,
    fails        INT          NOT NULL,
    locked_until TIMESTAMP NULL,
    last_attempt TIMESTAMP    NOT NULL,
    UNIQUE (username, ip)
);

CREATE INDEX idx_login_attempts_locked ON login_attempts (locked_until);

CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(150) NOT NULL,
    jti_hash   VARCHAR(64)  NOT NULL UNIQUE,
    expires_at TIMESTAMP    NOT NULL,
    revoked_at TIMESTAMP NULL
);

CREATE INDEX idx_refresh_user ON refresh_token (user_email);
CREATE INDEX idx_refresh_expires ON refresh_token (expires_at);

